$ErrorActionPreference = 'Continue'
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$src  = Join-Path $root 'src'

$files = Get-ChildItem -Path $src -Filter '*.js' | Sort-Object Name
if (-not $files) { Write-Host "[Build] No .js modules found in src\" -ForegroundColor Red; exit 1 }

$utf8 = New-Object System.Text.UTF8Encoding($false)
$parts = foreach ($f in $files) {
    $t = [IO.File]::ReadAllText($f.FullName, $utf8)
    if (-not $t.EndsWith("`n")) { $t += "`r`n" }
    $t
}
$body = $parts -join ''

# Mark the bundle as a generated artifact so nobody judges the single file as hand-written source
$header = @'
// ============================================================================
// SMART WAVE - GENERATED BUNDLE. DO NOT EDIT THIS FILE DIRECTLY.
// Modular source lives in src/ (01-core, 02-engine, 03-shader, 04-ui).
// Build: run Build-SmartWave.ps1 (concatenates src/*.js in order).
// ============================================================================

'@
$body = $header + $body
Write-Host ("[Build] Modules: " + ($files.Name -join ', ')) -ForegroundColor Cyan
Write-Host ("[Build] Total size: {0:N0} chars" -f $body.Length) -ForegroundColor Cyan

# 1. Sync repo copy (repo is the source of truth for marketplace)
$repoDir = Join-Path $root 'repo'
if (Test-Path $repoDir) {
    [IO.File]::WriteAllText((Join-Path $repoDir 'smartWave.js'), $body, $utf8)
    Write-Host "[Build] repo\smartWave.js updated" -ForegroundColor Green
    $repoSrc = Join-Path $repoDir 'src'
    if (Test-Path $repoSrc) { Remove-Item $repoSrc -Recurse -Force }
    Copy-Item $src $repoSrc -Recurse
    Copy-Item $PSCommandPath (Join-Path $repoDir 'Build-SmartWave.ps1') -Force
    Write-Host "[Build] repo\src synced" -ForegroundColor Green
}

# 2. Refresh installer payload inside Setup-SmartWave.bat
$setup = Join-Path $root 'Setup-SmartWave.bat'
if (Test-Path $setup) {
    $b64    = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($body))
    $chunks = [regex]::Matches($b64, '.{1,80}') | ForEach-Object { '::PAYLOAD::' + $_.Value }
    $batText = [IO.File]::ReadAllText($setup, $utf8)
    $marker  = '::PAYLOAD::'
    $idx = $batText.IndexOf($marker)
    if ($idx -ge 0) {
        $newBat = $batText.Substring(0, $idx) + ($chunks -join "`n") + "`n"
        [IO.File]::WriteAllText($setup, $newBat, $utf8)
        Write-Host "[Build] Setup-SmartWave.bat payload refreshed" -ForegroundColor Green
    }
}

# 3. Install + apply only when spicetify is present
$spicetify = Get-Command spicetify -ErrorAction SilentlyContinue
if ($spicetify) {
    $targets = @(
        (Join-Path $env:LOCALAPPDATA 'spicetify\Extensions\smartWave.js')
    )
    # Stray legacy copy in Roaming would double-inject the extension (two IIFE instances, split STATE) - remove it
    $legacy = Join-Path $env:APPDATA 'spicetify\Extensions\smartWave.js'
    if (Test-Path $legacy) { Remove-Item $legacy -Force; Write-Host "[Build] Removed legacy Roaming copy (double-injection guard)" -ForegroundColor Yellow }
    foreach ($t in $targets) {
        $dir = Split-Path -Parent $t
        if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
        [IO.File]::WriteAllText($t, $body, $utf8)
        Write-Host "[Build] Wrote $t" -ForegroundColor Green
    }
    Write-Host "[Build] Running spicetify apply..." -ForegroundColor Cyan
    spicetify apply
    Write-Host "[Build] Done. Restart Spotify to load the new build." -ForegroundColor Green
} else {
    Write-Host "[Build] Spicetify not installed - skipped local install. Push repo\ to publish." -ForegroundColor Yellow
}
